# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deque_create <- function() {
    .Call('container_deque_create', PACKAGE = 'container')
}

deque_release <- function(x) {
    invisible(.Call('container_deque_release', PACKAGE = 'container', x))
}

deque_empty <- function(x) {
    .Call('container_deque_empty', PACKAGE = 'container', x)
}

deque_size <- function(x) {
    .Call('container_deque_size', PACKAGE = 'container', x)
}

deque_push_back <- function(x, value) {
    invisible(.Call('container_deque_push_back', PACKAGE = 'container', x, value))
}

deque_push_front <- function(x, value) {
    invisible(.Call('container_deque_push_front', PACKAGE = 'container', x, value))
}

deque_pop_back <- function(x) {
    invisible(.Call('container_deque_pop_back', PACKAGE = 'container', x))
}

deque_pop_front <- function(x) {
    invisible(.Call('container_deque_pop_front', PACKAGE = 'container', x))
}

deque_back <- function(x) {
    .Call('container_deque_back', PACKAGE = 'container', x)
}

deque_front <- function(x) {
    .Call('container_deque_front', PACKAGE = 'container', x)
}

deque_at <- function(x, i) {
    .Call('container_deque_at', PACKAGE = 'container', x, i)
}

deque_as_list <- function(x) {
    .Call('container_deque_as_list', PACKAGE = 'container', x)
}

priority_queue_double_create <- function() {
    .Call('container_priority_queue_double_create', PACKAGE = 'container')
}

priority_queue_double_release <- function(x) {
    invisible(.Call('container_priority_queue_double_release', PACKAGE = 'container', x))
}

priority_queue_double_empty <- function(x) {
    .Call('container_priority_queue_double_empty', PACKAGE = 'container', x)
}

priority_queue_double_size <- function(x) {
    .Call('container_priority_queue_double_size', PACKAGE = 'container', x)
}

priority_queue_double_push <- function(x, value) {
    invisible(.Call('container_priority_queue_double_push', PACKAGE = 'container', x, value))
}

priority_queue_double_pop <- function(x) {
    invisible(.Call('container_priority_queue_double_pop', PACKAGE = 'container', x))
}

priority_queue_double_top <- function(x) {
    .Call('container_priority_queue_double_top', PACKAGE = 'container', x)
}

priority_queue_int_create <- function() {
    .Call('container_priority_queue_int_create', PACKAGE = 'container')
}

priority_queue_int_release <- function(x) {
    invisible(.Call('container_priority_queue_int_release', PACKAGE = 'container', x))
}

priority_queue_int_empty <- function(x) {
    .Call('container_priority_queue_int_empty', PACKAGE = 'container', x)
}

priority_queue_int_size <- function(x) {
    .Call('container_priority_queue_int_size', PACKAGE = 'container', x)
}

priority_queue_int_push <- function(x, value) {
    invisible(.Call('container_priority_queue_int_push', PACKAGE = 'container', x, value))
}

priority_queue_int_pop <- function(x) {
    invisible(.Call('container_priority_queue_int_pop', PACKAGE = 'container', x))
}

priority_queue_int_top <- function(x) {
    .Call('container_priority_queue_int_top', PACKAGE = 'container', x)
}

queue_create <- function() {
    .Call('container_queue_create', PACKAGE = 'container')
}

queue_release <- function(x) {
    invisible(.Call('container_queue_release', PACKAGE = 'container', x))
}

queue_empty <- function(x) {
    .Call('container_queue_empty', PACKAGE = 'container', x)
}

queue_size <- function(x) {
    .Call('container_queue_size', PACKAGE = 'container', x)
}

queue_push <- function(x, value) {
    invisible(.Call('container_queue_push', PACKAGE = 'container', x, value))
}

queue_pop <- function(x) {
    invisible(.Call('container_queue_pop', PACKAGE = 'container', x))
}

queue_back <- function(x) {
    .Call('container_queue_back', PACKAGE = 'container', x)
}

queue_front <- function(x) {
    .Call('container_queue_front', PACKAGE = 'container', x)
}

stack_create <- function() {
    .Call('container_stack_create', PACKAGE = 'container')
}

stack_release <- function(x) {
    invisible(.Call('container_stack_release', PACKAGE = 'container', x))
}

stack_empty <- function(x) {
    .Call('container_stack_empty', PACKAGE = 'container', x)
}

stack_size <- function(x) {
    .Call('container_stack_size', PACKAGE = 'container', x)
}

stack_push <- function(x, value) {
    invisible(.Call('container_stack_push', PACKAGE = 'container', x, value))
}

stack_pop <- function(x) {
    invisible(.Call('container_stack_pop', PACKAGE = 'container', x))
}

stack_top <- function(x) {
    .Call('container_stack_top', PACKAGE = 'container', x)
}

